stages:
  - Build

variables:
  LANG: "en_US.UTF-8"

image: "ruby:2.7.4"
before_script:
  - make

Build:
  stage: Build
  script:
    - make run_ci
  tags:
    - able_app
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  interruptible: true
